# 这是一个基本工作流，可帮助您开始操作

name: AppFeed本地化

# 控制工作流何时运行
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '* 0/2 * * *'
  push:
    branches:
      - main
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:  
        - {
          name: "AppFeed本地化部署",
          os: ubuntu-latest
          }
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@master
        
      # git克隆
      - name: Git Clone Action
        # 您可以锁定到确切的提交或版本.
        # uses: sudosubin/git-clone-action@8a93ce24d47782e30077508cccacf8a05a891bae
        uses: sudosubin/git-clone-action@v1.0.1
        with:
            # 存储库所有者和名称. Ex: sudosubin/git-clone-action
            repository: Squidly271/AppFeed # optional, default is ${{ github.repository }}
            # Git host platform. Ex: github, gitlab, bitbucket, gitee, or else (git.suckless.org, ...)
            platform: github # optional, default is github
            # Git branch or tag to checkout.
            ref: # optional
            # Relative path from current directory, where to clone.
            path: home/Squidly271/AppFeed # optional

      - name: Sync Repo to CODING
        uses: serverlesslife-cn/sync-repo-to-coding@master
        env:
            # 在 GitHub Settings->Secrets 配置 CODING_PRIVATE_KEY
            SSH_PRIVATE_KEY: ${{ secrets.CODING_PRIVATE_KEY }}
        with:
            # 注意替换为你的 GitHub 源仓库地址
            github-repo: "git@github.com:Squidly271/AppFeed.git"
            # 注意替换为你的 CODING 目标仓库地址
            coding-repo: "git@e.coding.net:juzhijian/unraidapp/AppFeed.git"

      - name: Git Repository Sync
        # You may pin to the exact commit or the version.
        # uses: net-engine/github-repository-sync-action@ab3e4e02cc6c4eed16c22040d7b409ae1d81bce4
        uses: net-engine/github-repository-sync-action@v1.2.0
        with:
            # 用于SSH连接到目标存储库的SSH私钥
            ssh_private_key: ${{ secrets.CODING_RSA_PRIVATE_KEY }} # optional
            # Target git repository URL
            target_repo_url: git@gitee.com:juzhijian/AppFeed.git

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo 拉取成功！

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.


