# 这是一个基本工作流，可帮助您开始操作

name: dynamix本地化

# 控制工作流何时运行
on:
  schedule:
    # 每2小时定时启动
    - cron:  '0 0/2 * * *'
  push:
    #特定分支(mian),
    #branches:
    #  - main
    #特定tsgs
    #tags:
    #  - v
    #特定路径
    paths:
      - 'dynamix/*'
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:  
        - {
          name: "同步dynamix",
          os: ubuntu-latest
          }
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Sync Repo to CODING
        uses: juzhijian/sync-repo-to-coding@master
        env:
            # 在 GitHub Settings->Secrets 配置 CODING_PRIVATE_KEY
            SSH_PRIVATE_KEY: ${{ secrets.CODING_PRIVATE_KEY }}
        with:
            # 注意替换为你的 GitHub 源仓库地址
            github-repo: "https://github.com/bergware/dynamix.git"
            # 注意替换为你的 CODING 目标仓库地址
            coding-repo: "git@e.coding.net:juzhijian/unraidapp/dynamix.git"
            # 仓库名称
            #appname: "dynamix"
            # 提交前运行sh
            wgetsh: "https://raw.githubusercontent.com/juzhijian/UnraidAPP/main/dynamix/main.sh"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo 多行命令本地化UnraidApp，
          echo 多行命令同步成功。

